version: "3.8"
services:
  db:
    image: mysql:8.0
    container_name: mysql_db_laravel
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: laravel
      MYSQL_DATABASE: 01-laravel-Task-List
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    volumes:
      - ./mysql:/var/lib/mysql


