services:
    db:
        image: mysql:8.0
        container_name: db
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: 04-livewire-poll
            MYSQL_USER: user
            MYSQL_PASSWORD: user
        ports:
            - "3306:3306"
        volumes:
            - ./db/db:/var/lib/mysql
