services:
    db:
        image: mysql:8.0
        container_name: db
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_USERNAME}
            MYSQL_DATABASE: ${DB_DATABASE}
        ports:
            - "${DB_PORT}:${DB_PORT}"
        volumes:
            - ./db:/var/lib/mysql
        networks:
            - app-network

    app:
        image: laravelphp/php-fpm
        container_name: laravel-app
        restart: unless-stopped
        build:
            context: .
            dockerfile: Dockerfile
        working_dir: /var/www
        volumes:
            - .:/var/www
        networks:
            - app-network

    web:
        image: nginx:alpine
        container_name: nginx
        restart: unless-stopped
        ports:
            - "8080:80"
        volumes:
            - .:/var/www
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - app-network
    redis:
        image: redis:alpine
        container_name: redis
        restart: unless-stopped
        networks:
        - app-network

networks:
    app-network:
        driver: bridge

