services:
    db:
        image: mysql:8.0
        container_name: db
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_USERNAME}
            MYSQL_DATABASE: ${DB_DATABASE}
        ports:
            - "${DB_PORT}:${DB_PORT}"
        volumes:
            - ./db:/var/lib/mysql
        networks:
            - app-network

    app:
        image: php:8.2-fpm
        container_name: laravel-app
        restart: unless-stopped
        build:
            context: .
            dockerfile: Dockerfile
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
        networks:
            - app-network

    webserver:
        image: nginx:latest
        container_name: nginx_server
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/html
            - ./nginx:/etc/nginx/conf.d
        depends_on:
            - app
        networks:
            - app-network

    redis:
        image: redis:alpine
        container_name: redis
        restart: unless-stopped
        networks:
        - app-network

networks:
    app-network:
        driver: bridge

